"""Parser for batch_metrics_*.csv generated by BatchMonitorDecorator.

Current format (v3):
    epoch, batch, n_batches, running_loss, batch_loss, lr, batch_f1, batch_acc, batch_prec

v2 format:
    epoch, batch, n_batches, running_loss, batch_loss, lr

Legacy format (v1):
    epoch, batch, n_batches, running_loss

All formats are supported — missing columns are filled with NaN.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

_ALL_COLS = ["epoch", "batch", "n_batches", "running_loss", "batch_loss", "lr",
             "batch_f1", "batch_acc", "batch_prec", "global_batch"]


def parse_batch_csv(csv_path: Path) -> pd.DataFrame:
    """Reads the per-batch metrics CSV and returns a normalized DataFrame.

    Guaranteed columns:
        epoch, batch, n_batches, running_loss, batch_loss, lr,
        batch_f1, batch_acc, batch_prec, global_batch

    Columns missing from the CSV are filled with NaN (legacy compatibility).
    """
    try:
        df = pd.read_csv(csv_path)
    except Exception:
        return pd.DataFrame(columns=_ALL_COLS)

    if df.empty:
        return pd.DataFrame(columns=_ALL_COLS)

    # Add new columns with NaN if missing (legacy/v2 CSV compatibility)
    for col in ("batch_loss", "lr", "batch_f1", "batch_acc", "batch_prec"):
        if col not in df.columns:
            df[col] = float("nan")

    # Global batch index (useful for showing the full training history)
    if "global_batch" not in df.columns:
        df["global_batch"] = (df["epoch"] - 1) * df["n_batches"] + df["batch"]

    return df
