"""Parse feasibility CSV generated by check_feasibility.py."""

from __future__ import annotations

from pathlib import Path

import pandas as pd


def parse_feasibility_csv(csv_path: Path) -> tuple[dict, pd.DataFrame]:
    """Return (metadata_dict, benchmark_df) from a feasibility CSV.

    The CSV has two '#meta' rows at the top followed by benchmark rows.
    """
    rows = []
    meta: dict = {}

    with open(csv_path, newline="") as f:
        import csv
        reader = csv.reader(f)
        header_meta: list[str] = []
        for row in reader:
            if not row:
                continue
            if row[0] == "#meta":
                if not header_meta:
                    header_meta = row[1:]
                else:
                    meta = dict(zip(header_meta, row[1:]))
            else:
                rows.append(row)

    if not rows:
        return meta, pd.DataFrame()

    header = rows[0]
    data = rows[1:]
    df = pd.DataFrame(data, columns=header)

    for col in ("batch_size", "s_per_batch", "imgs_per_s", "peak_vram_gb"):
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # Parse numeric columns for estimation columns (variable names based on epoch count)
    for col in df.columns:
        if col.startswith("est_"):
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # Normalize meta numeric fields
    for key in ("total_params_M", "flops_mflops", "total_vram_gb", "free_vram_gb"):
        if key in meta:
            try:
                meta[key] = float(meta[key])
            except (ValueError, TypeError):
                pass

    return meta, df
