"""Parse per-class metrics CSV generated by ConfusionMatrixDecorator."""

from __future__ import annotations

from pathlib import Path

import pandas as pd


def parse_perclass_csv(csv_path: Path) -> pd.DataFrame:
    """Return a DataFrame with columns: epoch, class_name, class_idx, f1, precision, recall."""
    df = pd.read_csv(csv_path)
    for col in ("f1", "precision", "recall"):
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
    return df
